---
language: ruby
cache: bundler
bundler_args: --without benchmarks tools
before_install:
  - gem update --system
  - gem install bundler --no-document
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
  - bundle exec rake
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.6
  - jruby-9.2.6.0
env:
  global:
    - COVERAGE=true
