name: Ruby

on: [push]

jobs:
  test-mri:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: ["2.6.x", "2.5.x", "2.4.x"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby_version}}
      - name: Build and test with Rake
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec

  test-jruby:
    runs-on: ubuntu-latest
    container:
      image: jruby:9.2
    steps:
      - uses: actions/checkout@v1
      - name: Install git
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git
      - name: Build and test with Rake
        run: |
          gem install bundler
          gem update --system
          bundle install --jobs 4 --retry 3
          bundle exec rspec
